---
title: "Project 0"
author: Shiyi Zhang
---
 
# About 

## Hi

I'm Shiyi Zhang, a first year ScM student of the Biostatisitcs Department. I graduated from Smith College with a B.A in Neuroscience. My past research experiences were mainly in the area molecular neuroscience i.e. signaling pathways of neurogenesis, molecular profile of adult neurogenesis. 

## Statistics Background

I found statistics very interesting in my third year at Smith through taking the multiple regression class with Dr.  Cook. I had little experience in programming and I wish to strengthen my relationship with programming languages through this class. 

## Fun Facts

1) I love binge-watching cooking shows.
2) My favorite color is green. 
3) I collected receipts, tags，coffee packaging.
4) I eat everything with cheese. (You should try goat cheese with Chinese buns)
5) When stressed, I start to make travel plans. 

## For Cooking Lovers

Click here to visit
[inspiring tips](https://modernistcuisine.com/mc/using-the-maillard-reaction-in-cooking/)





